#!/bin/bash

MAX_FREQ=3000000

echo 1 > /sys/module/processor/parameters/ignore_ppc

echo $MAX_FREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo $MAX_FREQ > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo $MAX_FREQ > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
echo $MAX_FREQ > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

